version: "3"
services: 
  formatter:
    build: .
    entrypoint: "/bin/formatter"
    depends_on: 
      - publisher
    restart: on-failure
    ports: 
      - "8081:8081"
    environment: 
       JAEGER_AGENT_HOST: collector

  publisher:
    build: .
    entrypoint: "/bin/publisher"
    restart: on-failure
    ports: 
      - "8082:8082"
    environment: 
       JAEGER_AGENT_HOST: collector

  collector:
    image: otel/opentelemetry-collector:0.37.0
    restart: on-failure
    command: [ "--config", "config.yml" ]
    volumes:
      - ./collector/config.yml:/config.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
  